apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::083739371673:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OI7DPTR7BJKV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::083739371673:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-26T01:07:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2043"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b26bb2da-fa31-4b80-8a19-dab0fef0b4ae
